# Schema for the views plugins of the Profile module.
views.field.activate_deactivate_profile_link:
  type: views.field.activate_deactivate_profile_link
  label: 'Link to activate/deactivate user profile'
